export const GETDATA_SUCCESS = "GETDATA_SUCCESS";
export const GETDATA_FAILED = "GETDATA_FAILED";

export const GETDATA_ENV_SUCCESS = "GETDATA_ENV_SUCCESS";
export const GETDATA_ENV_FAILED = "GETDATA_ENV_FAILED";

export const GETDATA_CHANNEL_SUCCESS = "GETDATA_CHANNEL_SUCCESS";
export const GETDATA_CHANNEL_FAILED = "GETDATA_CHANNEL_FAILED";
